### ISSUE TITLE
Dont generate all combinations

### ISSUE THREAD

**Issue by ghost** [madglory/permute_wordlist#1]
`leetDict = {
  'a': ['@', 'q'],
  'w': ['vv', 'w'],
  'l': ['|', 'i'],
}`

input:
`hola`
Output:
`ho|@
ho|q
hoi@
hoiq
`

Missing "ho|a" and "hoia"

Thanks

**Comment by MantisSTS** [comment]
Yeah I noticed the same. If I have time tonight I will create a pull-request fixing it if the author doesn't get around to doing so

**Comment by tquackenbush** [comment]
Hi. I think this fixes the issue:
https://github.com/madglory/permute_wordlist/commit/6dc0ed2cae8d5f95ebd8ff6afc7914137870142f

**Comment by tquackenbush** [comment]
Thanks for pointing this out. Let me know if there are any other issues.

**Comment by ghost** [comment]
Thanks and sorry for my bad english!
